
workspace:
  base: /go
  path: src/github.com/jmlambert78/golang-example
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
      - ls

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
